/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.0/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the application plugin to add support for building a CLI application in Java.
    application
    eclipse
}

val clientMainClass = "org.App"
val serverMainClass = "org.ServerApp"

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    implementation("org.slf4j:slf4j-api:2.0.17")
    runtimeOnly("ch.qos.logback:logback-classic:1.5.18")
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

// Apply a specific Java toolchain to ease working on different environments.

tasks.jar {
    manifest {
        attributes(
            "Main-Class" to clientMainClass
        )
    }
}

val clientJar by tasks.registering(Jar::class) {
    group = "build"
    description = "Builds a runnable client JAR."
    archiveClassifier.set("client")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(sourceSets.main.get().output)
    from({
        configurations.runtimeClasspath.get().map { dependency ->
            if (dependency.isDirectory) dependency else zipTree(dependency)
        }
    })
    manifest {
        attributes("Main-Class" to clientMainClass)
    }
}

val serverJar by tasks.registering(Jar::class) {
    group = "build"
    description = "Builds a runnable server JAR."
    archiveClassifier.set("server")
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    from(sourceSets.main.get().output)
    from({
        configurations.runtimeClasspath.get().map { dependency ->
            if (dependency.isDirectory) dependency else zipTree(dependency)
        }
    })
    manifest {
        attributes("Main-Class" to serverMainClass)
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    // Define the main class for the application.
    mainClass = clientMainClass
    applicationName = "app"
}

val runClient by tasks.registering(JavaExec::class) {
    group = "application"
    description = "Runs the client application."
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass.set(clientMainClass)
}

val runServer by tasks.registering(JavaExec::class) {
    group = "application"
    description = "Runs the server application."
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass.set(serverMainClass)
}

tasks.named<JavaExec>("run") {
    group = "application"
    description = "Runs the client application."
    classpath = sourceSets.main.get().runtimeClasspath
    mainClass.set(clientMainClass)
}

tasks.named("assemble") {
    dependsOn(clientJar, serverJar)
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
