package org.dataclasses;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Comparator;
import java.util.Objects;
import org.dataclasses.enums.MovieGenre;
import org.dataclasses.enums.MpaaRating;

/**
 * Класс для хранения данных о фильме.
 */

public class Movie implements Comparable<Movie>, Serializable {

    private static final long serialVersionUID = 1L;

    private static int minNotUsedId = 100000;
    private int id;
    private String name;
    private Coordinates coordinates;
    private LocalDateTime creationDate;
    private int oscarsCount;
    private MovieGenre genre;
    private MpaaRating mpaaRating;
    private Person operator;

    /**
     * Конструктор по умолчанию.
     * Создает фильм без автоматически генерируемых полей.
     */
    public Movie() {}

    /**
     * Конструктор с параметрами.
     * Создает фильм с указанными параметрами без автоматически генерируемых полей.
     * @param name название фильма (не может быть пустым или null)
     * @param coordinates координаты (не могут быть null)
     * @param oscarsCount количество оскаров (должно быть больше 0)
     * @param genre жанр фильма (не может быть null)
     * @param mpaaRating рейтинг MPAA (не может быть null)
     * @param operator оператор фильма (может быть null)
     * @throws IllegalArgumentException если name пустой или null
     * @throws IllegalArgumentException если coordinates равно null
     * @throws IllegalArgumentException если oscarsCount меньше или равно 0
     * @throws IllegalArgumentException если genre равно null
     * @throws IllegalArgumentException если mpaaRating равно null
     */
    public Movie(
        String name,
        Coordinates coordinates,
        int oscarsCount,
        MovieGenre genre,
        MpaaRating mpaaRating,
        Person operator
    ) {
        assignGeneratedFields();
        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException(
                "Movie.name cannot be empty or null"
            );
        }
        this.name = name;
        this.coordinates = Objects.requireNonNull(
            coordinates,
            "Movie.coordinates cannot be null"
        );
        if (oscarsCount <= 0) {
            throw new IllegalArgumentException(
                "Movie.oscarsCount must be greater than zero"
            );
        }
        this.oscarsCount = oscarsCount;
        this.genre = Objects.requireNonNull(
            genre,
            "Movie.genre cannot be null"
        );
        this.mpaaRating = Objects.requireNonNull(
            mpaaRating,
            "Movie.mpaaRating cannot be null"
        );
        this.operator = operator;
    }

    /**
     * Назначает автоматически генерируемые поля фильма.
     * Используется сервером при добавлении фильма в коллекцию.
     */
    public void assignGeneratedFields() {
        this.id = ++minNotUsedId;
        this.creationDate = LocalDateTime.now();
    }

    /**
     * Restores fields generated by persistent storage.
     *
     * @param id stored id
     * @param creationDate stored creation date
     */
    public void restoreGeneratedFields(int id, LocalDateTime creationDate) {
        if (id <= 0) {
            throw new IllegalArgumentException("Movie.id must be greater than zero");
        }
        this.id = id;
        this.creationDate = Objects.requireNonNull(
            creationDate,
            "Movie.creationDate cannot be null"
        );
        setMinNotUsedId(id);
    }

    /**
     * Устанавливает минимальный неиспользованный id.
     * Используется при загрузке коллекции из постоянного хранилища.
     * @param id минимальный неиспользованный id
     */
    public static void setMinNotUsedId(int id) {
        if (id > minNotUsedId) {
            minNotUsedId = id;
        }
    }

    /**
     * Сравнивает фильмы по названию, количеству оскаров и id.
     * Сначала сравнивается название, затем количество оскаров, затем id.
     * @param o фильм для сравнения
     * @return отрицательное число, если этот фильм меньше, положительное если больше, 0 если равны
     */
    @Override
    public int compareTo(Movie o) {
        if (o == null) {
            return 1;
        }
        return Comparator.comparing(Movie::getName)
            .thenComparingInt(Movie::getOscarsCount)
            .thenComparingInt(Movie::getId)
            .compare(this, o);
    }

    /**
     * Возвращает дату создания фильма.
     * @return дата создания фильма
     */
    public java.time.LocalDateTime getCreationDate() {
        return this.creationDate;
    }

    /**
     * Возвращает уникальный идентификатор фильма.
     * @return id фильма
     */
    public int getId() {
        return this.id;
    }

    /**
     * Возвращает название фильма.
     * @return название фильма
     */
    public String getName() {
        return this.name;
    }

    /**
     * Возвращает координаты фильма.
     * @return координаты фильма
     */
    public Coordinates getCoordinates() {
        return this.coordinates;
    }

    /**
     * Возвращает количество оскаров у фильма.
     * @return количество оскаров
     */
    public int getOscarsCount() {
        return this.oscarsCount;
    }

    /**
     * Возвращает жанр фильма.
     * @return жанр фильма
     */
    public MovieGenre getGenre() {
        return this.genre;
    }

    /**
     * Возвращает рейтинг MPAA фильма.
     * @return рейтинг MPAA
     */
    public MpaaRating getMpaaRating() {
        return this.mpaaRating;
    }

    /**
     * Возвращает оператора фильма.
     * @return оператор фильма (может быть null)
     */
    public Person getOperator() {
        return this.operator;
    }

    /**
     * Устанавливает название фильма.
     * @param name новое название фильма (не может быть пустым или null)
     * @throws IllegalArgumentException если name пустой или null
     */
    public void setName(String name) {
        if (name == null || name.isBlank()) {
            throw new IllegalArgumentException(
                "Movie.name cannot be empty or null"
            );
        }
        this.name = name;
    }

    /**
     * Устанавливает координаты фильма.
     * @param coordinates новые координаты фильма (не могут быть null)
     * @throws IllegalArgumentException если coordinates равно null
     */
    public void setCoordinates(Coordinates coordinates) {
        this.coordinates = Objects.requireNonNull(
            coordinates,
            "Movie.coordinates cannot be null"
        );
    }

    /**
     * Устанавливает количество оскаров фильма.
     * @param oscarsCount новое количество оскаров (должно быть больше 0)
     * @throws IllegalArgumentException если oscarsCount меньше или равно 0
     */
    public void setOscarsCount(int oscarsCount) {
        if (oscarsCount <= 0) {
            throw new IllegalArgumentException(
                "Movie.oscarsCount must be greater than zero"
            );
        }
        this.oscarsCount = oscarsCount;
    }

    /**
     * Устанавливает жанр фильма.
     * @param genre новый жанр фильма (не может быть null)
     * @throws IllegalArgumentException если genre равно null
     */
    public void setGenre(MovieGenre genre) {
        this.genre = Objects.requireNonNull(
            genre,
            "Movie.genre cannot be null"
        );
    }

    /**
     * Устанавливает рейтинг MPAA фильма.
     * @param mpaaRating новый рейтинг MPAA (не может быть null)
     * @throws IllegalArgumentException если mpaaRating равно null
     */
    public void setMpaaRating(MpaaRating mpaaRating) {
        this.mpaaRating = Objects.requireNonNull(
            mpaaRating,
            "Movie.mpaaRating cannot be null"
        );
    }

    private void setCreationDate(LocalDateTime creationDate) {
        this.creationDate = creationDate;
    }

    private void setId(int id) {
        this.id = id;
    }

    /**
     * Устанавливает оператора фильма.
     * @param operator новый оператор фильма (может быть null)
     */
    public void setOperator(Person operator) {
        this.operator = operator;
    }

    /**
     * Возвращает строковое представление фильма.
     * @return строковое представление фильма со всеми полями
     */
    @Override
    public String toString() {
        return (
            "Movie{" +
            "id=" +
            id +
            ", name='" +
            name +
            '\'' +
            ", coordinates=" +
            coordinates +
            ", creationDate=" +
            creationDate +
            ", oscarsCount=" +
            oscarsCount +
            ", genre=" +
            genre +
            ", mpaaRating=" +
            mpaaRating +
            ", operator=" +
            operator +
            '}'
        );
    }

    /**
     * Проверяет равенство фильмов.
     * Фильмы считаются равными, если у них одинаковые id.
     * @param o объект для сравнения
     * @return true если фильмы равны, false в противном случае
     */
    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Movie movie = (Movie) o;
        return id == movie.id;
    }

    /**
     * Возвращает хэш-код фильма.
     * Хэш-код вычисляется только на основе id.
     * @return хэш-код фильма
     */
    @Override
    public int hashCode() {
        return Integer.hashCode(id);
    }
}
