package org.db;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Objects;

/**
 * Creates the PostgreSQL schema required by Lab 7.
 */
public class SchemaInitializer {

    private final DatabaseConnector connector;

    public SchemaInitializer(DatabaseConnector connector) {
        this.connector = Objects.requireNonNull(
            connector,
            "Database connector cannot be null"
        );
    }

    /**
     * Creates missing schema objects.
     *
     * @throws SQLException if schema creation fails
     */
    public void initialize() throws SQLException {
        try (
            Connection connection = connector.getConnection();
            Statement statement = connection.createStatement()
        ) {
            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    login TEXT UNIQUE NOT NULL,
                    password_hash TEXT NOT NULL,
                    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
                """);
            statement.executeUpdate("""
                CREATE TABLE IF NOT EXISTS movies (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
                    collection_key TEXT NOT NULL,
                    owner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
                    name TEXT NOT NULL,
                    coordinates_x INTEGER NOT NULL,
                    coordinates_y INTEGER NOT NULL,
                    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    oscars_count INTEGER NOT NULL,
                    genre TEXT NOT NULL,
                    mpaa_rating TEXT NOT NULL,
                    operator_name TEXT,
                    operator_weight DOUBLE PRECISION,
                    operator_passport_id TEXT,
                    operator_nationality TEXT,
                    operator_location_x BIGINT,
                    operator_location_y DOUBLE PRECISION,
                    operator_location_name TEXT
                )
                """);
        }
    }
}
