/*
 * This source file was generated by the Gradle 'init' task
 */
package org;

import java.io.File;
import java.rmi.NoSuchObjectException;
import java.util.Arrays;
import java.util.Scanner;
import java.util.TreeMap;
import java.util.regex.Pattern;
import org.commands.CommandInvoker;
import org.commands.CommandParser;
import org.dataclasses.*;

public class App {

    private static String fileName;
    private static TreeMap<String, Movie> collection = new TreeMap<>();

    public static String getStorageFile() {
        return App.fileName;
    }

    public static TreeMap<String, Movie> getCollection() {
        return collection;
    }

    public static void main(String[] args) {
        if (args.length != 1) {
            System.out.println(
                "Usage: java -jar /path/to/.jar /path/to/inputfile.xml"
            );
            System.exit(1);
        }
        fileName = args[0];
        Pattern pattern = Pattern.compile(
            "<Movie.*?>.*?</Movie>",
            Pattern.DOTALL
        );

        File inputFile = new File(fileName);
        if (!inputFile.exists()) {
            System.out.println("no file found on path " + fileName);
            System.exit(0);
        } else if (!inputFile.canRead()) {
            System.out.println(
                "cant read the file on path " +
                    fileName +
                    ", chech read permissions"
            );
            System.exit(0);
        } else if (!inputFile.canWrite()) {
            System.out.println(
                "cant write the file on path " +
                    fileName +
                    ", chech write permissions"
            );
            System.exit(0);
        }
        try (Scanner scanner = new Scanner(inputFile, "UTF-8")) {
            while (scanner.findWithinHorizon(pattern, 0) != null) {
                Movie testmovie2 = Movie.fromXML(scanner.match().group(0));
                collection.put("" + testmovie2.getId(), testmovie2);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        // Location operatorLocation = new Location(515074L, -0.1278, "London");
        // Person movieOperator = new Person(
        //     "Christopher Nolan",
        //     78.5,
        //     "PASSPORT98765",
        //     Country.CHINA,
        //     operatorLocation
        // );
        // Coordinates movieCoordinates = new Coordinates(150, 350);

        // Movie testMovie = new Movie(
        //     "Inception",
        //     movieCoordinates,
        //     4, // oscarsCount > 0
        //     MovieGenre.ADVENTURE,
        //     MpaaRating.PG_13,
        //     movieOperator
        // );
        // collection.put(testMovie.getID(), testMovie);
        CommandParser userInputParser = new CommandParser(System.in);
        CommandInvoker invoker = new CommandInvoker();
        Movie movie;
        try {
            movie = userInputParser.parseObject(Movie.class);
            System.out.println(movie);
        } catch (Exception e) {
            e.printStackTrace();
        }
        System.out.print("> ");
        for (String[] command : userInputParser) {
            if (command[0] == "") {
                System.out.print("> ");
                continue;
            }
            try {
                invoker.invoke(
                    command[0],
                    Arrays.copyOfRange(command, 1, command.length)
                );
            } catch (NoSuchObjectException e) {
                System.out.println(e.getMessage());
            }
            System.out.print("> ");
        }
        userInputParser.close();
    }
}
