/*
 * This source file was generated by the Gradle 'init' task
 */
package org;

import java.io.FileNotFoundException;
import java.nio.file.AccessDeniedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.rmi.NoSuchObjectException;
import java.util.Arrays;
import java.util.Map;
import java.util.Scanner;
import java.util.TreeMap;
import java.util.regex.Pattern;
import org.commands.CommandInvoker;
import org.commands.InputParser;
import org.dataclasses.*;

public class App {

    private static String fileName;
    private static InputParser inputParser;
    private static TreeMap<String, Movie> collection = new TreeMap<>();

    public static String getStorageFile() {
        return App.fileName;
    }

    public static InputParser getInputParser() {
        return App.inputParser;
    }

    public static TreeMap<String, Movie> getCollection() {
        return collection;
    }

    public static void main(String[] args)
        throws FileNotFoundException, AccessDeniedException {
        if (args.length != 1) {
            System.out.println(
                "Usage: java -jar /path/to/.jar /path/to/inputfile.xml"
            );
            System.exit(1);
        }
        fileName = args[0];
        Pattern pattern = Pattern.compile(
            "<Movie.*?>.*?</Movie>",
            Pattern.DOTALL
        );

        Path inputPath = Paths.get(fileName);

        if (!Files.isWritable(inputPath)) {
            throw new AccessDeniedException(
                "cant write the file on path " +
                    fileName +
                    ", check write permissions"
            );
        }
        try (
            Scanner scanner = new Scanner(
                Files.newInputStream(inputPath),
                "UTF-8"
            )
        ) {
            while (scanner.findWithinHorizon(pattern, 0) != null) {
                Map.Entry<String, Movie> movie = Movie.fromXML(
                    scanner.match().group(0)
                );
                collection.put(movie.getKey(), movie.getValue());
            }
        } catch (FileNotFoundException e) {
            throw new FileNotFoundException(
                "no file found on path " + fileName
            );
        } catch (AccessDeniedException e) {
            throw new AccessDeniedException(
                "cant read the file on path " +
                    fileName +
                    ", check read permissions"
            );
        } catch (Exception e) {
            e.printStackTrace();
            inputParser.setInputStream(System.in);
        }
        // Location operatorLocation = new Location(515074L, -0.1278, "London");
        // Person movieOperator = new Person(
        //     "Christopher Nolan",
        //     78.5,
        //     "PASSPORT98765",
        //     Country.CHINA,
        //     operatorLocation
        // );
        // Coordinates movieCoordinates = new Coordinates(150, 350);

        // Movie testMovie = new Movie(
        //     "Inception",
        //     movieCoordinates,
        //     4, // oscarsCount > 0
        //     MovieGenre.ADVENTURE,
        //     MpaaRating.PG_13,
        //     movieOperator
        // );
        // collection.put(testMovie.getID(), testMovie);
        App.inputParser = new InputParser(System.in);
        CommandInvoker invoker = new CommandInvoker();
        System.out.print("> ");
        for (String[] command : App.inputParser) {
            if (command[0] == "") {
                System.out.print("> ");
                continue;
            }
            try {
                invoker.invoke(
                    command[0],
                    Arrays.copyOfRange(command, 1, command.length)
                );
            } catch (NoSuchObjectException e) {
                System.out.println(e.getMessage());
            }
            System.out.print("> ");
        }
        App.inputParser.close();
    }
}
