/*
 * This source file was generated by the Gradle 'init' task
 */
package org;

import java.io.FileNotFoundException;
import java.nio.file.AccessDeniedException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.Map;
import java.util.Scanner;
import java.util.TreeMap;
import java.util.regex.Pattern;
import org.commands.CommandInvoker;
import org.commands.InputParser;
import org.commands.ScannerInputSource;
import org.dataclasses.Movie;

/**
 * Главный класс приложения для управления коллекцией фильмов.
 * Загружает коллекцию из XML-файла и обрабатывает пользовательские команды.
 */
public class App {

    private static String fileName;
    private static InputParser inputParser;

    /**
     * Возвращает путь к файлу хранения коллекции.
     * @return путь к файлу
     */
    public static String getStorageFile() {
        return App.fileName;
    }

    /**
     * Возвращает парсер ввода.
     * @return экземпляр InputParser
     */
    public static InputParser getInputParser() {
        return App.inputParser;
    }

    /**
     * Главный метод приложения.
     * @param args аргументы командной строки (ожидается путь к XML-файлу)
     * @throws FileNotFoundException если файл не найден
     * @throws AccessDeniedException если нет доступа к файлу
     */
    public static void main(String[] args)
        throws FileNotFoundException, AccessDeniedException {
        if (args.length != 1) {
            System.out.println(
                "Usage: java -jar /path/to/.jar /path/to/inputfile.xml"
            );
            System.exit(1);
        }
        fileName = args[0];
        Pattern pattern = Pattern.compile(
            "<Movie.*?>.*?</Movie>",
            Pattern.DOTALL
        );

        Path inputPath = Paths.get(fileName);

        if (!Files.isWritable(inputPath)) {
            System.out.println(
                "cant write the file on path " +
                    fileName +
                    ", check write permissions"
            );
            System.exit(0);
        }

        TreeMap<String, Movie> loadedCollection = new TreeMap<>();
        try (
            Scanner scanner = new Scanner(
                Files.newInputStream(inputPath),
                "UTF-8"
            )
        ) {
            while (scanner.findWithinHorizon(pattern, 0) != null) {
                Map.Entry<String, Movie> movie = Movie.fromXML(
                    scanner.match().group(0)
                );
                loadedCollection.put(movie.getKey(), movie.getValue());
            }
        } catch (FileNotFoundException e) {
            throw new FileNotFoundException(
                "no file found on path " + fileName
            );
        } catch (AccessDeniedException e) {
            throw new AccessDeniedException(
                "cant read the file on path " +
                    fileName +
                    ", check read permissions"
            );
        } catch (Exception e) {
            e.printStackTrace();
        }

        CollectionManager cm = CollectionManager.getInstance();
        cm.setCollection(loadedCollection);

        App.inputParser = new InputParser(new ScannerInputSource(System.in));
        CommandInvoker invoker = new CommandInvoker();
        System.out.print("> ");
        for (String[] command : App.inputParser) {
            if (command[0] == "") {
                System.out.print("> ");
                continue;
            }
            try {
                String result = invoker.invoke(
                    command[0],
                    Arrays.copyOfRange(command, 1, command.length)
                );
                if (result != null && !result.isEmpty()) {
                    System.out.println(result);
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            System.out.print("> ");
        }
        App.inputParser.close();
    }
}
