/*
 * This source file was generated by the Gradle 'init' task
 */
package org;

import java.util.Arrays;
import javax.swing.SwingUtilities;
import org.commands.Command;
import org.commands.CommandFactory;
import org.commands.ClientCommandInvoker;
import org.commands.ClientContext;
import org.commands.InputParser;
import org.commands.ScannerInputSource;
import org.gui.MovieCollectionFrame;

/**
 * Клиентское приложение для отправки команд на сервер.
 */
public class App {

    /**
     * Главный метод приложения.
     * @param args аргументы командной строки: хост и порт сервера
     */
    public static void main(String[] args) {
        boolean consoleMode = args.length == 3 && "--console".equals(args[0]);
        if ((!consoleMode && args.length != 2) || (consoleMode && args.length != 3)) {
            System.out.println(
                "Usage: java -jar /path/to/.jar [--console] <server-host> <server-port>"
            );
            System.exit(1);
        }
        String serverHost = args[consoleMode ? 1 : 0];
        int serverPort;
        try {
            serverPort = Integer.parseInt(args[consoleMode ? 2 : 1]);
        } catch (NumberFormatException e) {
            System.out.println("\"" + args[consoleMode ? 2 : 1] + "\" is not a valid port");
            System.exit(1);
            return;
        }

        if (!consoleMode) {
            SwingUtilities.invokeLater(() ->
                new MovieCollectionFrame(serverHost, serverPort).setVisible(true)
            );
            return;
        }

        InputParser inputParser = new InputParser(
            new ScannerInputSource(System.in)
        );
        CommandFactory commandFactory = new CommandFactory(inputParser);
        ClientCommandInvoker commandInvoker = new ClientCommandInvoker(serverHost, serverPort);
        ClientContext clientContext = new ClientContext(
            inputParser,
            commandFactory,
            commandInvoker
        );
        clientContext.connect(new org.commands.ServerEndpoint(serverHost, serverPort));
        System.out.print("> ");
        for (String[] command : inputParser) {
            if (command.length == 0 || command[0].isEmpty()) {
                System.out.print("> ");
                continue;
            }
            try {
                String result = commandInvoker.invoke(
                    commandFactory.create(
                        command[0],
                        Arrays.copyOfRange(command, 1, command.length)
                    ),
                    clientContext
                );
                if (result != null && !result.isEmpty()) {
                    System.out.println(result);
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
            System.out.print("> ");
        }
        inputParser.close();
    }
}
